# The Elephant Shed's Prometheus config

global:
  scrape_interval: 30s
  evaluation_interval: 60s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
  #    monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  # scrape data from prometheus itself
  - job_name: prometheus
    scrape_interval: 300s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['localhost:9090']
  # scrape data from node_exporter
  - file_sd_configs:
    - files:
      - /etc/prometheus/node_exporter/*.yml
      refresh_interval: 15s
    job_name: node
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - regex: (.+)
      replacement: ${1};
      source_labels:
      - instance
      target_label: __tmp_instance
    - regex: ([^:;]+)((:[0-9]+)?|;(.*))
      replacement: ${1}
      separator: ''
      source_labels:
      - __tmp_instance
      - __address__
      target_label: instance
  # scrape data from sql_exporter
  - file_sd_configs:
    - files:
      - /etc/prometheus/sql_exporter/*.yml
      refresh_interval: 15s
    job_name: sql
    relabel_configs:
    - regex: (.+)
      replacement: ${1};
      source_labels:
      - instance
      target_label: __tmp_instance
    - regex: ([^:;]+)((:[0-9]+)?|;(.*))
      replacement: ${1}
      separator: ''
      source_labels:
      - __tmp_instance
      - __address__
      target_label: instance
