{
 "title": "PostgreSQL Server Overview",
 "description": "Overview over the most needed and many helpful metrics to manage and debug PostgreSQL servers.",
 "tags": [
  "prometheus",
  "system",
  "postgresql",
  "database"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Server",
    "query": {
     "query": "label_values(sql_settings{col='max_connections'}, instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(sql_settings{instance='$instance'}, sql_job)"
    }
   },
   {
    "name": "host",
    "label": "PostgreSQL Port",
    "query": {
     "query": "label_values(sql_settings{instance='$instance'}, host)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(sql_pg_stat_database{col='dbsize', host=~'$host', instance=~'$instance', sql_job=~'$cluster'}, datname)"
    }
   },
   { "name": "rate_interval", "label": "Rate Interval", "query": "1m,5m,10m,30m,1h" },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(node_disk_written_bytes_total, device)"
    }
   },
   { "name": "ntop_relations", "label": "Top k", "query": "1,3,5,10,20,50,100" },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(node_network_receive_bytes_total, device)"
    }
   },
   {
    "name": "filesystem",
    "label": "Filesystem",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{instance='$instance'}, mountpoint)"
    }
   },
   {
    "name": "application_name",
    "label": "Streaming Receiver",
    "query": {
     "query": "label_values(sql_pg_stat_replication{host=~'$host', instance=~'$instance', sql_job=~'$cluster'}, application_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sql_server{host=~'$host',instance=~'$instance',sql_job=~'$cluster',col=\"server_start_time\"}",
     "legendFormat": "{{server_version}}"
    }
   ]
  },
  {
   "title": "# Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total) without (mode, instance, job)) without (cpu)"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"max_connections\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"work_mem\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"shared_buffers\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"max_wal_size\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Data Checksums",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"data_checksums\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Checksum Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (checksum_failures) (sql_pg_stat_database{col=\"checksum_failures\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'})"
    }
   ]
  },
  {
   "title": "Server Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_server{col=\"server_start_time\", host=~'$host',instance=~'$instance',sql_job=~'$cluster'} * 1000"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"max_worker_processes\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"maintenance_work_mem\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Effective Cache Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"effective_cache_size\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Checkpoint Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"checkpoint_timeout\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "JIT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sql_settings{col=\"jit\",host=~'$host',instance=~'$instance',sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "Out-of-Memory Kills",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_vmstat_oom_kill{instance=~'$instance'}"
    }
   ]
  },
  { "title": "Summary for $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU [$rate_interval]",
   "type": "singlestat",
   "description": "The CPU usage, rate over $rate_interval.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~'$instance'}[$rate_interval])) * 100)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (node_memory_MemFree_bytes{instance=~'$instance'} + node_memory_Buffers_bytes{instance=~'$instance'} + node_memory_Cached_bytes{instance=~'$instance'}) / node_memory_MemTotal_bytes{instance=~'$instance'}"
    }
   ]
  },
  {
   "title": "Max Used Storage",
   "type": "singlestat",
   "description": "Shows the percentage of used storage on the most used mount.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - min(node_filesystem_free_bytes{instance=~'$instance', mountpoint=~'$filesystem'} / node_filesystem_size_bytes{instance=~'$instance', mountpoint=~'$filesystem'})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "description": "Percentage of swap spaced used on system",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$instance'} / (node_memory_SwapCached_bytes{instance=~'$instance'} + node_memory_SwapFree_bytes{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "Next Freeze",
   "type": "singlestat",
   "description": "Age of oldest XID in percent of autovacuum_max_freeze_age (default: 200 M)\n\nAt 100%, tables will be frozen by autovacuum. Values over 100% indicate autovacuum is not keeping up.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', datname=~'$datname', col='freeze_age'}) / max(sql_settings{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='autovacuum_freeze_max_age'})",
     "legendFormat": "{{ host }}/{{ datname }}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "description": "The used connections in relation to the limit (reduced by superuser_reserved_connections).",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg_over_time(sql_pg_stat_activity{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col=\"count\"}[$rate_interval])) / (sum(sql_settings{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='max_connections'}) - sum(sql_settings{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='superuser_reserved_connections'}))"
    }
   ]
  },
  {
   "title": "WAL Files Ready",
   "type": "singlestat",
   "description": "Number of WAL files that still need to be archived.\n\nCan grow under write load but should not increase over longer periods of time.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sql_archive_ready{host=~'$host', instance=~'$instance', sql_job=~'$cluster'}"
    }
   ]
  },
  {
   "title": "WAL Ready Growth [1h]",
   "type": "singlestat",
   "description": "The amount of WAL data that still needs to be archived.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 14 },
   "format": "MBs",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(sql_archive_ready{host=~'$host', instance=~'$instance', sql_job=~'$cluster'}[1h]) * 16 / 3600"
    }
   ]
  },
  {
   "title": "WAL Archive Fails [$rate_interval]",
   "type": "singlestat",
   "description": "Shows the rate/increase in failed archive actions.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "increase(sql_pg_stat_archiver{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='failed_count'}[$rate_interval])"
    }
   ]
  },
  {
   "title": "WAL Senders",
   "type": "singlestat",
   "description": "Active WAL senders in relation to max_wal_senders.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sql_pg_stat_replication{host=~'$host', instance=~'$instance', sql_job=~'$cluster', pid!='0', col='flush_lag_bytes'})/ scalar(sql_settings{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='max_wal_senders'})"
    }
   ]
  },
  {
   "title": "Prepared Transactions",
   "type": "singlestat",
   "description": "Shows the used prepared transactions in relation to max_prepared_transactions.\n\n'N/A' if not used.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 14 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sql_prepared_transactions{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='count', datname=~'$datname'}) / sum(sql_settings{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='max_prepared_transactions'})"
    }
   ]
  },
  {
   "title": "Max Replication Lag",
   "type": "singlestat",
   "description": "Shows the maximum of send_lag_bytes, flush_lag_bytes, replay_lag_bytes over all connected streaming receivers.\nThis is not a sufficient way to monitor if a standby is up to date!\nCan only give a hint if streaming is delayed.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 14 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sql_pg_stat_replication{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col=~'(send_lag_bytes|flush_lag_bytes|replay_lag_bytes)'})"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU Usage (by mode) [$rate_interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{mode!='idle', instance=~'$instance'}[$rate_interval]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Usage (by core) [$rate_interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{mode!='idle', instance=~'$instance'}[$rate_interval]))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~'$instance'} - (node_memory_MemFree_bytes{instance=~'$instance'} + node_memory_Buffers_bytes{instance=~'$instance'} + node_memory_Cached_bytes{instance=~'$instance'})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$instance'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Dirty",
   "type": "graph",
   "description": "Modified memory that needs to be written back to permanent storage.",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Dirty_bytes{instance=~'$instance'}",
     "legendFormat": "Memory Dirty"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$instance'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_SwapFree_bytes{instance=~'$instance'}",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Filesystem $filesystem", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Filesystem - \"$filesystem\"",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "repeat": "filesystem",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=~'$filesystem', instance=~'$instance'} - node_filesystem_avail_bytes{mountpoint=~'$filesystem', device!~'rootfs', instance=~'$instance'}",
     "legendFormat": "Used \"{{mountpoint}}\" ({{device}}, {{fstype}})"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=~'$filesystem', device!~'rootfs', instance=~'$instance'}",
     "legendFormat": "Free \"{{mountpoint}}\" ({{device}}, {{fstype}})"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Read/Write (IOPS) [$rate_interval] - $disk",
   "type": "graph",
   "description": "Reads are shown above the \nzero line (>0) and writes are shown below (<0).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "iops", "label": "Read/Write (bytes)" }
   ],
   "targets": [
    {
     "expr": "-1 * irate(node_disk_writes_completed_total{device=~'$disk', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Writes (completed) {{device}}"
    },
    {
     "expr": "-1 * irate(node_disk_writes_merged_total{device=~'$disk', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Writes (merged) {{device}}"
    },
    {
     "expr": "irate(node_disk_reads_completed_total{device=~'$disk', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Reads (completed) {{device}}"
    },
    {
     "expr": "irate(node_disk_reads_merged_total{device=~'$disk', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Reads (merged) {{device}}"
    }
   ]
  },
  {
   "title": "Read/Write (bytes) [$rate_interval] - $disk",
   "type": "graph",
   "description": "Reads are shown above the \nzero line (>0) and writes are shown below (<0).",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "Bps", "label": "Read/Write (bytes)" }
   ],
   "targets": [
    {
     "expr": "-1 * irate(node_disk_written_bytes_total{device=~'$disk', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Write {{device}}"
    },
    {
     "expr": "irate(node_disk_read_bytes_total{device=~'$disk', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Read {{device}}"
    }
   ]
  },
  {
   "title": "Read/Write Time [$rate_interval] - $disk",
   "type": "graph",
   "description": "Reads are shown above the \nzero line (>0) and writes are shown below (<0).",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "s", "label": "Read/Write Time" }
   ],
   "targets": [
    {
     "expr": "-1 * irate(node_disk_write_time_seconds_total{device=~'$disk', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Writes {{device}}"
    },
    {
     "expr": "irate(node_disk_read_time_seconds_total{device=~'$disk', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Read {{device}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Network Traffic [$rate_interval] - $interface",
   "type": "graph",
   "description": "RX is shown above the \nzero line (>0) and TX is shown below (<0).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{device=~'$interface', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Received {{device}}"
    },
    {
     "expr": "-1 * irate(node_network_transmit_bytes_total{device=~'$interface', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Send {{device}}"
    }
   ]
  },
  {
   "title": "Network Packets [$rate_interval] - $interface",
   "type": "graph",
   "description": "RX is shown above the \nzero line (>0) and TX is shown below (<0).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{device=~'$interface', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Received {{device}}"
    },
    {
     "expr": "-1 * irate(node_network_transmit_packets_total{device=~'$interface', instance=~'$instance'}[$rate_interval])",
     "legendFormat": "Send {{device}}"
    }
   ]
  },
  { "title": "PostgreSQL Database Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Database Growth [$rate_interval] - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', datname=~'$datname', col='dbsize'}[$rate_interval])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Database Size - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', datname=~'$datname', col='dbsize'}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "PostgreSQL Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Connections by State - $datname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (state) (sql_pg_stat_activity{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='count', datname=~'$datname'}))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connections by Database - $datname",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (sql_pg_stat_activity{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='count', datname=~'$datname'})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Transactions and Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 }
  },
  {
   "title": "Transactions by database [$rate_interval] - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='xact_commit', datname=~'$datname'}[$rate_interval]))",
     "legendFormat": "commits {{datname}}"
    },
    {
     "expr": "sum by (datname) (rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='xact_rollback', datname=~'$datname'}[$rate_interval]))",
     "legendFormat": "rollbacks {{datname}}"
    },
    {
     "expr": "rate(sql_txid{host=~'$host', instance=~'$instance', sql_job=~'$cluster'}[$rate_interval])",
     "legendFormat": "TXIDs (global)"
    }
   ]
  },
  {
   "title": "Maximum Transaction Age",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 81 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (datname) (sql_pg_stat_activity{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='max_tx_duration', datname=~'$datname'})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Locks - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (sql_pg_locks{host=~'$host', instance=~'$instance', sql_job=~'$cluster', datname=~'$datname'}) by (mode)",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Deadlocks -$datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='deadlocks', datname=~'$datname'}[90s]) * 60",
     "legendFormat": "deadlocks {{datname}}"
    }
   ]
  },
  { "title": "PostgreSQL Tuple Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Read Stats [$rate_interval] - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', datname=~'$datname', col='tup_returned'}[$rate_interval])",
     "legendFormat": "Select (table scan) {{datname}}"
    },
    {
     "expr": "rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', datname=~'$datname', col='tup_fetched'}[$rate_interval])",
     "legendFormat": "Select (index scan) {{datname}}"
    }
   ]
  },
  {
   "title": "Live Tuples (top $ntop_relations) - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($ntop_relations, sql_pg_stat_user_tables{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', col='n_live_tup', datname=~'$datname'})",
     "legendFormat": "live {{schemaname}}.{{relname}} ({{database}})"
    }
   ]
  },
  {
   "title": "Change Stats [$rate_interval] - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short", "label": "Rows" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', datname=~'$datname', col='tup_inserted'}[$rate_interval])",
     "legendFormat": "Insert {{datname}}"
    },
    {
     "expr": "rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', datname=~'$datname', col='tup_updated'}[$rate_interval])",
     "legendFormat": "Update {{datname}}"
    },
    {
     "expr": "rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', datname=~'$datname', col='tup_deleted'}[$rate_interval])",
     "legendFormat": "Delete {{datname}}"
    }
   ]
  },
  {
   "title": "Dead Tuples (top $ntop_relations) - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($ntop_relations, sql_pg_stat_user_tables{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', col='n_dead_tup', database=~'$datname'})",
     "legendFormat": "dead {{schemaname}}.{{relname}} ({{database}})"
    }
   ]
  },
  {
   "title": "Temp Files  [$rate_interval] - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 96 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "rate(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', col='temp_bytes', database=~'$datname'}[$rate_interval])",
     "legendFormat": "temp bytes {{database}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Table/Index Scans and Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 }
  },
  {
   "title": "Sequential Scan Tuples [$rate_interval] (top $ntop_relations) - $datname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($ntop_relations, rate(sql_pg_stat_user_tables{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', col='seq_tup_read', database=~'$datname'}[$rate_interval]))",
     "legendFormat": "seq scan tuples {{schemaname}}.{{relname}} ({{database}})"
    }
   ]
  },
  {
   "title": "Index Scan Tuples [$rate_interval] (top $ntop_relations) - $datname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 104 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk($ntop_relations, rate(sql_pg_stat_user_tables{host=~'$host', instance=~'$instance', sql_job=~'$cluster.*', col='idx_tup_fetch', database=~'$datname'}[$rate_interval]))",
     "legendFormat": "index scan tuples {{schemaname}}.{{relname}} ({{database}})"
    }
   ]
  },
  {
   "title": "Buffer Hit Rate [$rate_interval] - $datname",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 104 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', datname=~'$datname', col='blks_hit'}[$rate_interval])) / (sum(increase(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', datname=~'$datname', col='blks_read'}[$rate_interval])) + sum(increase(sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', datname=~'$datname', col='blks_hit'}[$rate_interval])))",
     "legendFormat": "hit rate"
    }
   ]
  },
  {
   "title": "PostgreSQL Transaction Log and Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 }
  },
  {
   "title": "WAL/Checkpoint Traffic [$rate_interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(sql_waldistance{host=~'$host', instance=~'$instance', sql_job=~'$cluster'}[$rate_interval])",
     "legendFormat": "WAL traffic"
    },
    {
     "expr": "rate(sql_checkpoints{col=\"buffers\", host=~'$host', instance=~'$instance', sql_job=~'$cluster'}[$rate_interval]) * 8192",
     "legendFormat": "Checkpoint traffic"
    }
   ]
  },
  {
   "title": "Checkpoints per Minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 113 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "60 * rate(sql_checkpoints{host=~'$host', instance=~'$instance', sql_job=~'$cluster'}[90s])",
     "legendFormat": "{{col}}"
    }
   ]
  },
  {
   "title": "WAL since last Checkpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 113 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sql_LastCheckpointDistance{host=~'$host', instance=~'$instance', sql_job=~'$cluster'}",
     "legendFormat": "{{col}}"
    }
   ]
  },
  { "title": "PostgreSQL Vacuum and Analyze", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Maintenance Operations per Minute [$rate_interval] - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "60 * rate(sql_Maintenancecounters{host=~'$host', sql_job=~'$cluster.*', datname=~'$datname'}[$rate_interval])",
     "legendFormat": "{{col}} ({{database}})"
    }
   ]
  },
  {
   "title": "Maintenance Counters - $datname",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sql_Maintenancecounters{host=~'$host', sql_job=~'$cluster.*', database=~'$datname'}",
     "legendFormat": "{{col}} ({{database}})"
    }
   ]
  },
  {
   "title": "Database Freeze Age - $datname",
   "type": "graph",
   "description": "Age of oldest XID in database\n\nWhen reaching autovacuum_max_freeze_age (default: 200 M), tables will be frozen by autovacuum.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_database{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='freeze_age', datname=~'$datname'}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "PostgreSQL Archiving and Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 }
  },
  {
   "title": "WAL Files Ready",
   "type": "graph",
   "description": "Number of WAL files that still need to be archived.\n\nCan grow under write load but should not increase over longer periods of time.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sql_archive_ready{host=~'$host', instance=~'$instance', sql_job=~'$cluster'}",
     "legendFormat": "WAL Files Ready"
    }
   ]
  },
  {
   "title": "WAL Archiving per Minute [$rate_interval]",
   "type": "graph",
   "description": "Successful and failed archive commands per minute.",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 129 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "60 * rate(sql_pg_stat_archiver{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col=~'archived_count|failed_count'}[$rate_interval])",
     "legendFormat": "{{col}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "description": "The amount of data a stream receiver like a standby server lags behind the master.\n\nsend_lag: Data that still needs to be send (should be small).\n\nflush_lag: Data that was received but must be flushed to persistent storage (this data can be lost if the standby is terminated).\n\nreplay_lag: Data that still needs to be replayed by PostgreSQL on the standby (can lag behind during writes in asynchronous configurations).",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 129 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sql_pg_stat_replication{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='send_lag_bytes', application_name != ''}",
     "legendFormat": "{{application_name}} (send)"
    },
    {
     "expr": "sql_pg_stat_replication{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='flush_lag_bytes', application_name != ''}",
     "legendFormat": "{{application_name}} (flush)"
    },
    {
     "expr": "sql_pg_stat_replication{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='replay_lag_bytes', application_name != ''}",
     "legendFormat": "{{application_name}} (replay)"
    },
    {
     "expr": "sql_pg_stat_replication{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col=~'replay_lag_bytes|flush_lag_bytes|send_lag_bytes', application_name=''}>0",
     "legendFormat": "MISSING application_name ({{col}})"
    }
   ]
  },
  { "title": "PostgreSQL Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Top $ntop_relations Statements by Average Execution Time [$rate_interval] - $datname",
   "type": "graph",
   "description": "Statement average execution time",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($ntop_relations, rate(sql_pg_stat_statements{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='total_time', datname=~'$datname'}[$rate_interval]) / ignoring(col) rate(sql_pg_stat_statements{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='calls', datname=~'$datname'}[$rate_interval]))",
     "legendFormat": "({{datname}}) {{query}}"
    }
   ]
  },
  {
   "title": "Top $ntop_relations Statements by Total Time [$rate_interval] - $datname",
   "type": "graph",
   "description": "Statement execution time per second",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 137 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "topk($ntop_relations, rate(sql_pg_stat_statements{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='total_time', datname=~'$datname'}[$rate_interval]))",
     "legendFormat": "({{datname}}) {{query}}"
    }
   ]
  },
  {
   "title": "Top $ntop_relations Statements by Calls [$rate_interval] - $datname",
   "type": "graph",
   "description": "Statements called per second",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 137 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "topk($ntop_relations, rate(sql_pg_stat_statements{host=~'$host', instance=~'$instance', sql_job=~'$cluster', col='calls', datname=~'$datname'}[$rate_interval]))",
     "legendFormat": "({{datname}}) {{query}}"
    }
   ]
  },
  {
   "title": "Top $ntop_relations Statements by Total Time - $datname",
   "type": "table",
   "description": "Shows how long statements took in the chosen time period.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk($ntop_relations, increase(sql_pg_stat_statements{host=~'$host', instance=~'$instance', sql_job=~'$cluster', host=~'$host', col='total_time', datname=~'$datname'}[$__range]))"
    }
   ]
  }
 ]
}