#!/bin/sh

set -e

HOSTNAME=$(hostname -f)

case $1 in
  configure)
    systemctl daemon-reload

    systemctl enable prometheus-sql-exporter.service
    systemctl restart prometheus-sql-exporter.service
    systemctl enable prometheus-sql-exporter-restart.timer
    systemctl start prometheus-sql-exporter-restart.timer

    if [ ! -e /etc/prometheus/sql_exporter/$HOSTNAME.yml ]; then
      mkdir -p /etc/prometheus/sql_exporter
      echo "- targets:" > /etc/prometheus/sql_exporter/$HOSTNAME.yml
      echo "    - $HOSTNAME:9237" >> /etc/prometheus/sql_exporter/$HOSTNAME.yml
    fi
    ;;
esac

#DEBHELPER#
